# This is a basic workflow to help you get started with Actions

name: Staging CI

on:
  push:
    branches: [ "staging" ]
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run php-cs-fixer
        run: make setup

  test:
    name: Test the code
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v3
      - name: Run php-cs-fixer
        run: docker run --rm --name=linter --workdir="/project" -v .:/project php:8.1.19-alpine3.16 php ./vendor/bin/php-cs-fixer fix ./src --dry-run --diff --using-cache=yes
      - name: Run phpstan
        run: docker run --rm --name=linter --workdir="/project" -v .:/project php:8.1.19-alpine3.16 php ./vendor/bin/phpstan analyse ./src
      - name: Run codecept
        run: docker run --rm --name=linter --workdir="/project" -v .:/project php:8.1.19-alpine3.16 php ./vendor/bin/codecept run

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run a one-line script Deploy
        run: echo "Deploy to staging"
